spring:
  datasource:
    url: jdbc:mysql://119.23.188.171:3306/timeline?serverTimezone=GMT
    username: guest1
    password: guest123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    配了也没执行
#    schema: classpath:timeline.sql
#    dbcp2:
#      min-idle: 5                                   # 数据库连接池的最小维持连接数
#      initial-size: 5                               # 初始化提供的连接数
#      max-total: 5                                  # 最大的连接数
#      max-wait-millis: 200                          # 等待连接获取的最大超时时间
